### ISSUE TITLE
Crash in dev

### ISSUE THREAD

**Issue by mezz** [AtomicBlom/HomecraftMineware#1]
I placed down a large bed in my dev environment test world and crashed:
https://gist.github.com/mezz/aa6139a09b64d8ff54355cf3351e8749

**Comment by SDUBZ** [comment]
same here mezz :/ but i mostly testing for 1.11.2 compat myself
[crash-2017-01-04_16.10.11-client.txt](https://github.com/AtomicBlom/HomecraftMineware/files/683963/crash-2017-01-04_16.10.11-client.txt)

**Comment by AtomicBlom** [comment]
That's not cool.

Looks like I was still developing on 1.11.0, I'll update to 1.11.2 and let's see if that fixes it for you.

**Comment by AtomicBlom** [comment]
Please try again, I've updated the code to 1.11.2.

There's a new build on curseforge as well.

**Comment by mezz** [comment]
Works now, thanks!
