### ISSUE TITLE
Blocks could need some resistence

### ISSUE THREAD

**Issue by Terpo** [AtomicBlom/HomecraftMineware#12]
You should extend your base block a bit: (examples)
this.setResistance(2F);    --> Blast protection
this.setHardness(2F);      --> Breaking protection
this.setHarvestLevel("pickaxe", 2); --> Tool and level 

I don't think that it is intentional that you can break most blocks with nearly the power of your eyes :D

**Comment by AtomicBlom** [comment]
Come live in my house for a day and you'll think it's normal ;D

They're good suggestions that definately should have been in there since the beginning. I'll fix it with the next update.

**Comment by AtomicBlom** [comment]
Fixed in HCMW 0.3.0.1
