### ISSUE TITLE
Strange crash

### ISSUE THREAD

**Issue by TheDarkPreacher** [AtomicBlom/HomecraftMineware#13]
loaded up the world, turned, and crashed. was working fine the other day. crashlog said "Ticking Particle" and mentioned it was from Homecraft Mineware. only thing that might have caused it was the two lanterns I have placed that I turned towards.

paste of crashlog: https://pastebin.com/2S3VtACQ

**Comment by AtomicBlom** [comment]
Huh, that's a funny bug. Looks like it was trying to set a bed on fire.

Cheers for the report @TheDarkPreacher, I might try doing a stream tonight to get it fixed.

Investigation
========
No, not really, but a particle was having issues doing collision detection against a bed. 

It appears that a smoke particle did a collision detection against a StructureShapeBlock, it located the structure, but was then unable to resolve the Structure, resulting in a NPE on StructureBlock.getPattern

**Comment by AtomicBlom** [comment]
I tried to reproduce the bug and couldn't in my dev environment which leads me to think that perhaps the bed lost it's structure key somehow?

Upon further investigation, I think I'll need to change how the keys are managed and move to using a Registry instead. I'll need to drag @FoudroyantFactotum into the discussion to decide on how to move forward.

**Comment by AtomicBlom** [comment]
I encountered this bug while testing 0.3.1 and found that it occurs when Collision boxes are accessed before Tile Entities are fully loaded? I've worked around it by ignoring the collision box if the tile entity isn't ready yet.

Give 0.3.1 a try. PLEASE let me know if you end up with log spam, as I do log when this happens.
