### ISSUE TITLE
[1.11.2] update neighbours - server crash

### ISSUE THREAD

**Issue by Terpo** [AtomicBlom/HomecraftMineware#14]
https://gist.github.com/Terpo/27e20bdba7fa85e4ddf7b5afdcc1d6e0
forge 2282
hcmw 1.11.2-0.2.9

Can't tell you what happened exactly because I was not on the server when it crashes.

**Comment by AtomicBlom** [comment]
Thanks for the bug report. Looks like someone tried blowing up a bed with TNT?

I'll see about getting a fix for this asap.

**Comment by Terpo** [comment]
One of my pack testers blew up a village as far as I know.

**Comment by Terpo** [comment]
https://gist.github.com/Terpo/4d693410f662f83cb44f2977ded32ea6
https://gist.github.com/Terpo/cf0722a66fceddd5407b42a223badcc8
https://gist.github.com/Terpo/059aae47c61f2b9b8234f6ea2d841fa9
I don't see much difference in this crashes, but there you go :D

**Comment by AtomicBlom** [comment]
Please give HCMW 0.3.0.1 a go and see if that fixes your issues.
