### ISSUE TITLE
Crash with TOP

### ISSUE THREAD

**Issue by ghost** [AtomicBlom/HomecraftMineware#15]
https://github.com/McJty/TheOneProbe/issues/162

**Comment by AtomicBlom** [comment]
I wasn't able to reproduce this in development or with a clean install of Forge, TOP, CompatLayer and HCMW (I used the same versions as your logs.)

I did however identify a part of the code that might have caused problems and fixed that, so give HCMW 0.3.0.1 a try and see if that fixes your issues.

**Comment by ghost** [comment]
latest version of hcmw is fine. thanks!
