### ISSUE TITLE
"Issues" button on CurseForge should link here

### ISSUE THREAD

**Issue by mezz** [AtomicBlom/HomecraftMineware#2]
The "Issues" button on CurseForge should link here,
and I think the readme here should link back to CurseForge.
Just makes thing easier to find.

**Comment by AtomicBlom** [comment]
Fixed, but ideally, I probably want to hook it up to issues.steamnsteel.info which is where I'm actually working from. I just need to investigate whether the Service Desk stuff will do what I want it to.
