### ISSUE TITLE
Unexpected Error when right clicking Lantern & Candle Holder (: 

### ISSUE THREAD

**Issue by Beanius** [AtomicBlom/HomecraftMineware#4]
https://gist.github.com/1256bbad5c830884dad982a35684cc22

**Comment by AtomicBlom** [comment]
Thanks for the bug report. It seems easy to fix. I'll work on it tonight.

**Comment by Beanius** [comment]
Ait super! Looking forward to the update B) Keep up the good work ^^,

**Comment by AtomicBlom** [comment]
Hi Beanius, it should be fixed for you with the latest build, let me know how you go.

**Comment by Beanius** [comment]
Aye it's working B) Thank you.
