### ISSUE TITLE
crash on load up (1.11.2) forge-2214

### ISSUE THREAD

**Issue by SDUBZ** [AtomicBlom/HomecraftMineware#5]
[crash-2017-01-12_23.33.57-client.txt](https://github.com/AtomicBlom/HomecraftMineware/files/701691/crash-2017-01-12_23.33.57-client.txt)

updated forge today and a few mods and got this crash on load up

**Comment by ghost** [comment]
yeah im agreeing this happening on me too

**Comment by AtomicBlom** [comment]
Ugh. Forge added a thing I've been hoping they'd do for a while, but did it in a way that I wasn't coding for.
https://github.com/MinecraftForge/MinecraftForge/pull/3621

I'll have to make my code a bit more defensive.

**Comment by SDUBZ** [comment]
loads up fine now thanks atomic :D

**Comment by AtomicBlom** [comment]
Nice, thanks for getting back to me.
