### ISSUE TITLE
fluid crate needs dumby proofing

### ISSUE THREAD

**Issue by SDUBZ** [AtomicBlom/HomecraftMineware#6]
i was testing to see if i could insert anything inside the fluid crate ui and i deciced to test with shift clicking a bed and it crashed the game
[crash-2017-01-13_23.57.33-client.txt](https://github.com/AtomicBlom/HomecraftMineware/files/704940/crash-2017-01-13_23.57.33-client.txt)

**Comment by AtomicBlom** [comment]
Oh ffs. I've seen this before -_-

Note for myself:
I think this fixed the same error in SteamNSteel:
https://github.com/SteamNSteel/SteamNSteel/commit/cfe17e6b0c1284ada26683903f9652a72a8deff3#diff-d07498b454e4f383d24cbe309d579f56R33

**Comment by AtomicBlom** [comment]
Fixed in 0.2
